apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-application
  labels:
    app: flask-application
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-application
  template:
    metadata:
      labels:
        app: flask-application
    spec:
      containers:
      - name: flask-application
        image: mohdzaid099/zaid_flask:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        env:
        - name: FLASK_ENV
          value: "production"
